# --- Identity ---------------------------------------------------------------
variable "aws_region" {
  type    = string
  default = "ap-northeast-1"
}

variable "project_name" {
  description = "Prefix for resource names. Must match project_name in ../bootstrap"
  type        = string
  default     = "auth-service"
}

variable "environment" {
  type = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

# --- Image ------------------------------------------------------------------
variable "image_tag" {
  description = "Image tag in the ECR repository created by ../bootstrap (CI passes the git commit SHA)"
  type        = string
}

# --- Network ----------------------------------------------------------------
variable "vpc_cidr" {
  type    = string
  default = "10.30.0.0/16"
}

variable "az_count" {
  description = "Number of AZs (ALB and the RDS subnet group need at least 2)"
  type        = number
  default     = 2

  validation {
    condition     = var.az_count >= 2
    error_message = "az_count must be at least 2."
  }
}

# --- Load balancer ----------------------------------------------------------
variable "certificate_arn" {
  description = "ACM certificate for HTTPS on the ALB. Empty = HTTP only (credentials travel in clear text: dev only!)"
  type        = string
  default     = ""
}

# --- Compute ----------------------------------------------------------------
variable "container_port" {
  type    = number
  default = 8080
}

variable "task_cpu" {
  description = "Fargate task CPU units (256 = 0.25 vCPU)"
  type        = number
  default     = 512
}

variable "task_memory" {
  description = "Fargate task memory in MiB"
  type        = number
  default     = 1024
}

variable "desired_count" {
  type    = number
  default = 1
}

variable "cpu_architecture" {
  description = "X86_64 or ARM64. Must match the platform the image is built for in CI"
  type        = string
  default     = "X86_64"

  validation {
    condition     = contains(["X86_64", "ARM64"], var.cpu_architecture)
    error_message = "cpu_architecture must be X86_64 or ARM64."
  }
}

variable "use_fargate_spot" {
  description = "Run tasks on FARGATE_SPOT (~70% cheaper, can be interrupted)"
  type        = bool
  default     = false
}

variable "enable_execute_command" {
  description = "Allow `aws ecs execute-command` into running containers"
  type        = bool
  default     = false
}

variable "log_retention_days" {
  type    = number
  default = 14
}

# --- Database ---------------------------------------------------------------
variable "db_engine_version" {
  description = "RDS MySQL major version; minor versions are upgraded automatically"
  type        = string
  default     = "8.4"
}

variable "db_instance_class" {
  type    = string
  default = "db.t4g.micro"
}

variable "db_allocated_storage" {
  description = "Initial storage in GiB (storage autoscaling up to db_max_allocated_storage)"
  type        = number
  default     = 20
}

variable "db_max_allocated_storage" {
  type    = number
  default = 100
}

variable "db_name" {
  type    = string
  default = "auth_service"
}

variable "db_username" {
  type    = string
  default = "auth_service"
}

variable "db_multi_az" {
  type    = bool
  default = false
}

variable "db_backup_retention_days" {
  type    = number
  default = 7
}

variable "db_deletion_protection" {
  type    = bool
  default = true
}

variable "db_skip_final_snapshot" {
  type    = bool
  default = false
}

# --- Secrets ----------------------------------------------------------------
# Generated by Terraform and written write-only: they never land in the state.
# Bump a version to rotate the secret; the ECS service is redeployed automatically.
variable "db_password_version" {
  type    = number
  default = 1
}

variable "jwt_secret_version" {
  description = "Rotating the JWT secret invalidates every issued token"
  type        = number
  default     = 1
}

# --- Application ------------------------------------------------------------
variable "jwt_access_token_ttl" {
  type    = string
  default = "15m"
}

variable "jwt_refresh_token_ttl" {
  type    = string
  default = "7d"
}
